Retter mindre skrivefeil
bouvet/sikkerhet.bouvet.no pull request #102
Opened 2023-05-05 09:11 UTC by vstenvik

Retter bare noen mindre skrivefeil

Ser også at "angrepsmetoder" er brukt som to titler i samme liste, burde den første vært noe annet?

2023-05-05 11:00 UTC, soofstad approved these changes

2023-05-05 11:38 UTC, askaret requested changes

2023-05-05 11:38 UTC, askaret commented on docs/checklist.md
> +[Angrepsmetoder](https://sikkerhet.bouvet.no/utvikle/kildekode#angreps-metoder):
Kan vel fjernes, gitt at den ovenfor oppdateres?

2023-05-05 11:38 UTC, askaret commented on docs/checklist.md
> +[Angrepsmetoder](https://sikkerhet.bouvet.no/utvikle/kildekode/#angreps-metoder):
Endre teksten under til noe slikt?
- Er teamet kjent med de meste vanlige agrepsmetodene, slik som manglende validering av data?

2023-06-30 13:15 UTC, vstenvik commented on docs/checklist.md
```suggestion
```

2023-06-30 13:16 UTC, vstenvik commented on docs/checklist.md
> +[Angrepsmetoder](https://sikkerhet.bouvet.no/utvikle/kildekode/#angreps-metoder):
```suggestion
[Er teamet kjent med de meste vanlige agrepsmetodene, slik som manglende validering av data?](https://sikkerhet.bouvet.no/utvikle/kildekode/#angreps-metoder):
```

2023-07-03 07:21 UTC, askaret approved these changes

2023-07-03 07:21 UTC, merged